#!/bin/sh
set -e

# Starting docker-compose services
docker-compose up -d

sleep 10

docker-compose exec kafka kafka-topics --bootstrap-server kafka:29093 --create --topic test \
--partitions 1 --replication-factor 1 --command-config /etc/kafka/admin.properties

echo "Example configuration to access kafka:"
echo "-> docker-compose exec kafka kafka-console-producer --broker-list localhost:9092 --topic test --producer.config /etc/kafka/client.properties"
echo "-> docker-compose exec kafka kafka-console-consumer --bootstrap-server localhost:9092 --topic test --consumer.config /etc/kafka/client.properties --from-beginning"
