version: '3'
services:

    zookeeper:
      image: confluentinc/cp-zookeeper:5.3.0
      hostname: zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

    kafka:
        build: kafka/
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9093:9093"
            - "29093:29093"
        command: ["kafka-server-start", "/etc/kafka/server.properties"]
