---
version: '2'
services:

  kafka1:
    image: confluentinc/cp-enterprise-kafka:${TAG}
    container_name: kafka1
    ports:
      - 9092:9092
      - 9101:9101
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:39092,2@kafka2:39093,3@kafka3:39094'
      KAFKA_LISTENERS: 'CONTROLLER://kafka1:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./configure:/etc/confluent/docker/configure
      - ./configure_run.sh:/tmp/configure_run.sh
      - ./kafka/1/:/etc/kafka/
      - ./tmp/1/:/tmp
    command: "bash -c 'if [ ! -f /tmp/configure_run.sh ]; then echo \"ERROR: Did you forget the configure_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/configure_run.sh && /etc/confluent/docker/run ; fi'"

  kafka2:
      image: confluentinc/cp-enterprise-kafka:${TAG}
      container_name: kafka2
      ports:
        - 9093:9093
        - 9102:9102
      environment:
        KAFKA_BROKER_ID: 2
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_JMX_PORT: 9102
        KAFKA_JMX_HOSTNAME: localhost
        KAFKA_PROCESS_ROLES: 'controller'
        KAFKA_NODE_ID: 2
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:39092,2@kafka2:39093,3@kafka3:39094'
        KAFKA_LISTENERS: 'CONTROLLER://kafka2:39093'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      volumes:
        - ./configure:/etc/confluent/docker/configure
        - ./configure_run.sh:/tmp/configure_run.sh
        - ./kafka/2/:/etc/kafka/
        - ./tmp/2/:/tmp
      command: "bash -c 'if [ ! -f /tmp/configure_run.sh ]; then echo \"ERROR: Did you forget the configure_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/configure_run.sh && /etc/confluent/docker/run ; fi'"

  kafka3:
      image: confluentinc/cp-enterprise-kafka:${TAG}
      container_name: kafka3
      ports:
        - 9094:9094
        - 9103:9103
      environment:
        KAFKA_BROKER_ID: 3
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_JMX_PORT: 9103
        KAFKA_JMX_HOSTNAME: localhost
        KAFKA_PROCESS_ROLES: 'controller'
        KAFKA_NODE_ID: 3
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:39092,2@kafka2:39093,3@kafka3:39094'
        KAFKA_LISTENERS: 'CONTROLLER://kafka3:39094'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      volumes:
        - ./configure:/etc/confluent/docker/configure
        - ./configure_run.sh:/tmp/configure_run.sh
        - ./kafka/3/:/etc/kafka/
        - ./tmp/3/:/tmp
      command: "bash -c 'if [ ! -f /tmp/configure_run.sh ]; then echo \"ERROR: Did you forget the configure_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/configure_run.sh && /etc/confluent/docker/run ; fi'"

  kafka4:
      image: confluentinc/cp-enterprise-kafka:${TAG}
      container_name: kafka4
      ports:
        - 9095:9095
        - 9104:9104
      environment:
        KAFKA_BROKER_ID: 4
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka4:29095,PLAINTEXT_HOST://localhost:9095'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_JMX_PORT: 9104
        KAFKA_JMX_HOSTNAME: localhost
        KAFKA_PROCESS_ROLES: 'broker'
        KAFKA_NODE_ID: 4
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:39092,2@kafka2:39093,3@kafka3:39094'
        KAFKA_LISTENERS: 'PLAINTEXT://kafka4:29095,PLAINTEXT_HOST://0.0.0.0:9095'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      volumes:
        - ./configure_run.sh:/tmp/configure_run.sh
        - ./kafka/4/:/etc/kafka/
        - ./tmp/4/:/tmp
      command: "bash -c 'if [ ! -f /tmp/configure_run.sh ]; then echo \"ERROR: Did you forget the configure_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/configure_run.sh && /etc/confluent/docker/run ; fi'"
