#!/usr/bin/env bash

mkdir -p kafka tmp
MODE=$1
FILE="docker-compose-one.yaml"

if [ "$MODE" = "compact" ]
then
  FILE="docker-compose-compact.yaml"
elif  [ "$MODE" = "one" ]
then
  FILE="docker-compose-one.yaml"
elif  [ "$MODE" = "iso" ]
then
  FILE="docker-compose-iso.yaml"
fi

printf "starting mode $MODE\n"

docker-compose -f $FILE up -d
