---
version: '2'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:${TAG}
    container_name: zookeeper00
    hostname: zookeeper00
    volumes:
      - "$PWD/zookeeper/0:/etc/kafka"
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: "zookeeper00:22888:23888;zookeeper01:2888:3888;zookeeper02:2888:3888"
      #KAFKA_OPTS: '-Dzookeeper.4lw.commands.whitelist=* -Djava.security.auth.login.config=/etc/kafka/zookeeper.sasl.jaas.config -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -DrequireClientAuthScheme=sasl'

  zookeeper01:
      image: confluentinc/cp-zookeeper:${TAG}
      container_name: zookeeper01
      hostname: zookeeper01
      volumes:
        - "$PWD/zookeeper/1:/etc/kafka"
      ports:
        - 2182:2182
      environment:
        ZOOKEEPER_SERVER_ID: 2
        ZOOKEEPER_CLIENT_PORT: 2182
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_SERVERS: "zookeeper00:22888:23888;zookeeper01:2888:3888;zookeeper02:2888:3888"
        #KAFKA_OPTS: '-Dzookeeper.4lw.commands.whitelist=* -Djava.security.auth.login.config=/etc/kafka/zookeeper.sasl.jaas.config -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -DrequireClientAuthScheme=sasl'

  zookeeper02:
      image: confluentinc/cp-zookeeper:${TAG}
      container_name: zookeeper02
      hostname: zookeeper02
      volumes:
        - "$PWD/zookeeper/2:/etc/kafka"
      ports:
        - 2183:2183
      environment:
        ZOOKEEPER_SERVER_ID: 3
        ZOOKEEPER_CLIENT_PORT: 2183
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_SERVERS: "zookeeper00:22888:23888;zookeeper01:2888:3888;zookeeper02:2888:3888"
        #KAFKA_OPTS: '-Dzookeeper.4lw.commands.whitelist=* -Djava.security.auth.login.config=/etc/kafka/zookeeper.sasl.jaas.config -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -DrequireClientAuthScheme=sasl'

  kafka:
    image: confluentinc/cp-enterprise-kafka:${TAG}
    depends_on:
      - zookeeper
      - zookeeper01
      - zookeeper02
    container_name: kafka
    volumes:
      - "$PWD/kafka:/etc/kafka"
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper00:2181,zookeeper01:2182,zookeeper02:2183
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,INTERNAL://kafka:29093,EXTERNAL://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_AUTHORIZER_CLASS_NAME: 'kafka.security.authorizer.AclAuthorizer'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
      KAFKA_SUPER_USERS: 'User:kafka;User:ANONYMOUS'
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
        username=\"kafka\" \
        password=\"kafka\" \
        user_kafka=\"kafka\" \
        user_alice=\"alice-secret\";"
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
        username=\"kafka\" \
        password=\"kafka\" \
        user_kafka=\"kafka\" \
        user_alice=\"alice-secret\";"
      #KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf'
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=DEBUG"


  kafka-connect:
    build:
      context: kafka-connect/
      dockerfile: Dockerfile
    container_name: kafka-connect
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - 18083:18083
    environment:
      CUB_CLASSPATH: '/usr/share/java/confluent-security/connect/*:/usr/share/java/kafka/*:/usr/share/java/cp-base-new/*'
      CLASSPATH: "/usr/share/java/kafka-connect-replicator/*:/usr/share/java/monitoring-interceptors/*:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/jars/*"
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LISTENERS: http://0.0.0.0:18083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _kafka-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _kafka-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _kafka-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components,/usr/local/share/kafka/plugins,/usr/share/filestream-connectors
      CONNECT_REST_EXTENSION_CLASSES: org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension
      KAFKA_OPTS: -Djava.security.auth.login.config=/tmp/connect.jaas
    volumes:
      - $PWD/scripts:/scripts
      - $PWD/jars:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/jars

  schema-registry:
    image: confluentinc/cp-schema-registry:${TAG}
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8089:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper00:2181'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
